# ===================================================================
# Spring Boot Configuration for PostgreSQL Database (Cloud & Local)
# ===================================================================

# Server Port
server.port=${PORT:8080}

# PostgreSQL Datasource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.qvfzamhcjefearagbera.supabase.co:5432/postgres?user=postgres&password=${DB_PASSWORD}


# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson / JSON Configuration
spring.jackson.serialization.fail-on-empty-beans=false
